### ISSUE TITLE
[Question] Is it possible to inject initContainers?

### ISSUE THREAD

**Issue by rjshrjndrn** [ExpediaGroup/kubernetes-sidecar-injector#16]
Hi,
Thanks for this great plugin. I had one question, is it possible to use this to inject init containers, as well as sidecar?

**Comment by mchandramouli** [comment]
@rjshrjndrn  Yes. By adding `initContainers`  [here](https://github.com/ExpediaDotCom/kubernetes-sidecar-injector/blob/master/webhook/mutator.go#L164)  and updating [this method](https://github.com/ExpediaDotCom/kubernetes-sidecar-injector/blob/master/webhook/mutator.go#L164) to handle the injection. Not too hard - few lines in that method.  Unfortunately I dont have access to this repo anymore. We can see if @ayansen  or anyone @ExpediaEngineering can do this or they can merge a PR
