### ISSUE TITLE
Multiple patches leads to incorrect JSON patch path

### ISSUE THREAD

**Issue by mwm5945** [ExpediaGroup/kubernetes-sidecar-injector#42]
If multiple items are specified in the ConfigMap, i.e. multiple Init Containers, volumes, etc, the `createArrayPatches` function will incorrectly append `/-` to the path, even though it has already been updated. This results in an error from the replica controller stating that the Patch Path is missing keys.  Example of what happens when trying to add two volumes for a side car: 

```
Internal error occurred: add operation does not apply: doc is missing path: "/spec/volumes/-/-": missing value
```
Removing the second volume fixes the issue.

**Comment by mvaalexp** [comment]
Closing as the PR has been merged.
